import AVFoundation
import Foundation
import MXAudioCore
import MXAudioDSP

/// A booted, UI-free engine plus its offline renderer.
///
/// Every integration and golden-audio test starts from one of these, so a
/// failure is attributable to the graph under test rather than to differences
/// in how a suite happened to set the engine up.
public final class MXHeadlessEngine {

    public let graph: MXGraph
    public let transport: MXTransport
    public let renderer: MXOfflineRenderer
    public let sampleRate: Double

    /// Directory for fixtures generated by this instance; removed on teardown.
    public let workingDirectory: URL

    public init(sampleRate: Double = 48_000,
                blockFrames: AVAudioFrameCount = 512) throws {
        self.sampleRate = sampleRate
        workingDirectory = try MXFixtureFactory.makeTemporaryDirectory()
        graph = MXGraph(sampleRate: sampleRate)
        transport = MXTransport(tempoMap: MXTempoMap(bpm: 145),
                                sampleRate: sampleRate,
                                clockSource: .offline)
        renderer = MXOfflineRenderer(graph: graph,
                                     sampleRate: sampleRate,
                                     blockFrames: blockFrames)
    }

    public func start() throws {
        try renderer.prepare()
    }

    public func tearDown() {
        graph.stop()
        try? FileManager.default.removeItem(at: workingDirectory)
    }

    // MARK: - Convenience

    /// Adds a track carrying `instrument` and returns both.
    @discardableResult
    public func addTrack(named name: String = "Track",
                         instrument: MXInstrument) -> MXTrackChain {
        graph.addTrack(name: name, instrument: instrument)
    }

    /// Renders `seconds` with a single note held for `holdSeconds`.
    ///
    /// This is the shape of most I-* scenarios, so it lives here rather than
    /// being retyped in each suite.
    public func renderNote(_ note: UInt8,
                           velocity: UInt8 = 100,
                           on instrument: MXInstrument,
                           holdSeconds: Double = 1.0,
                           totalSeconds: Double = 2.0) throws -> MXRenderResult {
        try renderer.render(seconds: totalSeconds, actions: [
            MXScheduledAction(at: 0.0) {
                instrument.noteOn(note, velocity: velocity, channel: 0)
            },
            MXScheduledAction(at: holdSeconds) {
                instrument.noteOff(note, channel: 0)
            },
        ])
    }

    public func render(seconds: Double,
                       actions: [MXScheduledAction] = []) throws -> MXRenderResult {
        try renderer.render(seconds: seconds, actions: actions)
    }

    public func fixtureURL(_ name: String) -> URL {
        workingDirectory.appendingPathComponent(name)
    }
}
